// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7cuSjFCsaAhezYmneeW0gBQ42R5ns7Ts',
    appId: '1:669299278585:web:d6aaa096fa363eb1e59828',
    messagingSenderId: '669299278585',
    projectId: 'urbanruchi',
    authDomain: 'urbanruchi.firebaseapp.com',
    storageBucket: 'urbanruchi.appspot.com',
    measurementId: 'G-YKWZH2M5GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCz4T7fWvTxkM51tyzDNe4H-fTP96x5mI',
    appId: '1:669299278585:android:a7b93ac2e2f71cd3e59828',
    messagingSenderId: '669299278585',
    projectId: 'urbanruchi',
    storageBucket: 'urbanruchi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDedEqKd_cIX-rIGUvag65nrEtyrYUUhxE',
    appId: '1:669299278585:ios:534b950830792c5fe59828',
    messagingSenderId: '669299278585',
    projectId: 'urbanruchi',
    storageBucket: 'urbanruchi.appspot.com',
    iosBundleId: 'com.tunkinnovations.testingproback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDedEqKd_cIX-rIGUvag65nrEtyrYUUhxE',
    appId: '1:669299278585:ios:534b950830792c5fe59828',
    messagingSenderId: '669299278585',
    projectId: 'urbanruchi',
    storageBucket: 'urbanruchi.appspot.com',
    iosBundleId: 'com.tunkinnovations.testingproback',
  );
}
