// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-8YndqEv0FEXE2T4LHpZVo3vSt-SdDdI',
    appId: '1:181185644616:web:e819f5a96e7de35393b07d',
    messagingSenderId: '181185644616',
    projectId: 'testingproback',
    authDomain: 'testingproback.firebaseapp.com',
    databaseURL: 'https://testingproback-default-rtdb.firebaseio.com',
    storageBucket: 'testingproback.appspot.com',
    measurementId: 'G-9XQLG15P7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArOsbcBXadBwEXtMsxDUaUjMDKUKyOu8o',
    appId: '1:181185644616:android:6ce042ca6847246d93b07d',
    messagingSenderId: '181185644616',
    projectId: 'testingproback',
    databaseURL: 'https://testingproback-default-rtdb.firebaseio.com',
    storageBucket: 'testingproback.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz8K7YjZTszjjWcvA5hHitUwh2QXjFub8',
    appId: '1:181185644616:ios:f1b4391f1411a74a93b07d',
    messagingSenderId: '181185644616',
    projectId: 'testingproback',
    databaseURL: 'https://testingproback-default-rtdb.firebaseio.com',
    storageBucket: 'testingproback.appspot.com',
    androidClientId: '181185644616-juhb43b79bdre7n4c8utlcg94scv58dr.apps.googleusercontent.com',
    iosClientId: '181185644616-8vf9nnpi5c4eninb642ik8m8f5s51mb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingproback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz8K7YjZTszjjWcvA5hHitUwh2QXjFub8',
    appId: '1:181185644616:ios:f1b4391f1411a74a93b07d',
    messagingSenderId: '181185644616',
    projectId: 'testingproback',
    databaseURL: 'https://testingproback-default-rtdb.firebaseio.com',
    storageBucket: 'testingproback.appspot.com',
    androidClientId: '181185644616-juhb43b79bdre7n4c8utlcg94scv58dr.apps.googleusercontent.com',
    iosClientId: '181185644616-8vf9nnpi5c4eninb642ik8m8f5s51mb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingproback',
  );
}
